#!/usr/bin/env bash
#
# Modify /etc/hosts to set up an ad free browsing experience
# Thanks to https://github.com/StevenBlack/hosts

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

if test "$(uname)" != "Darwin"
then
  fail "Only MacOS is supported as of now."
  exit 0
fi

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

info "Cloning hosts files..."

# Cloning the repo to a temporary location.
git clone https://github.com/StevenBlack/hosts.git ./tmp/hosts --depth 1

success "Successfully cloned the repo..."

user "Overwrite current hosts file?"
read -e -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
  info "Backing up current host file to tmp/bakup/hosts.bk"
  mkdir -p tmp/bakup
  rm tmp/bakup/hosts.bk
  sudo mv /etc/hosts tmp/bakup/hosts.bk
  success "Backed up current hosts file to tmp/bakup/hosts.bk"
  info "Copying Host file to /etc/hosts"
  sudo cp tmp/hosts/hosts /etc/hosts
  success "All Good."
else
  fail "Well, its on you."
fi
